### PR TITLE
Move source file to this official repository

### PR DESCRIPTION
**Pull request by DrFaust92**

### CODE REVIEW

**Comment by DrFaust92** [comment]
Updated to latest values while I was at it.

**Review by khos2ow — COMMENTED** [review]
Thanks @DrFaust92! This looks great. I have two questions though:

- what does the release process look like?
  - on  a new release of the binary we need to update `$checksum` and `$url`?
- can we add a CI or Actions of some sort on this?
  - I've found https://github.com/marketplace/actions/chocolatey-action, is this useful for us in this context?

**Comment by DrFaust92** [comment]
Ive been doing this manually but the process is `choco pack` & `choco push`. 
The version in the main file needs to be updated as well.
Ill for some GitHub action maybe but a simple script can we written as well. Can you open a user on https://chocolatey.org <https://chocolatey.org/> and share the username? Ill share the package ownership with it and with that user we can do the automation.

**Comment by khos2ow** [comment]
Alright, sounds great. So let's proceed with this PR and add some sort of automation on a PR of its own.

**Review by khos2ow — APPROVED** [review]

**Comment by khos2ow** [comment]
I've signed up, this is the profile: https://chocolatey.org/profiles/terraform-docs, is this enough on your side?

**Comment by khos2ow** [comment]
Partially fixes https://github.com/terraform-docs/terraform-docs/issues/220 and https://github.com/DrFaust92/chocolatey-packages/issues/3.

**Pull request merged**
